# Generated by Django 4.0 on 2022-08-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_agenda_id'),
        ('products', '0004_remove_product_receipt_id_product_agenda_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='agenda_id',
            new_name='agenda_receipt_id',
        ),
        migrations.AddField(
            model_name='product',
            name='Receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
        ),
    ]
