# Generated by Django 4.0 on 2022-08-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_agenda_id_product_agenda_receipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agenda_receipt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
