# Generated by Django 4.0 on 2022-10-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_payment_facturable_electronica_alter_payment_amount_and_more'),
        ('receipts', '0010_alter_receipt_created_at_alter_receipt_updated_at'),
        ('products', '0006_alter_product_agenda_receipt_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='product',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt', verbose_name='recibo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='agenda_receipt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='recibo_id_agenda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_display',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='detalles_vendedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
    ]
