# Generated by Django 4.0 on 2022-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_alter_product_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_display',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='producto nombre'),
        ),
    ]
