# Generated by Django 4.0 on 2022-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('location_name', models.IntegerField()),
                ('employee_code_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=200)),
            ],
        ),
    ]
