# Generated by Django 4.0 on 2022-08-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('installments', models.IntegerField(null=True)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_method_type', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('location_id', models.IntegerField(null=True)),
                ('location_name', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(null=True)),
                ('change_amount', models.IntegerField(null=True)),
                ('employee_code_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
        ),
    ]
