# Generated by Django 4.0 on 2022-08-04 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='change_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='paid_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payments',
            name='location_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='location_name',
            field=models.IntegerField(null=True),
        ),
    ]
