# Generated by Django 4.0 on 2022-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_change_amount_payments_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('location_id', models.IntegerField(null=True)),
                ('location_name', models.IntegerField(null=True)),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(null=True)),
                ('change_amount', models.IntegerField(null=True)),
                ('employee_code_id', models.IntegerField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
