# Generated by Django 4.0 on 2022-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_delete_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('installments', models.IntegerField(null=True)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_method_type', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
            ],
        ),
    ]
