version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: shalonapp_django
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - "3306"
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: shalonapp_celeryworker
    depends_on:
      - redis
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: shalonapp_celerybeat
    depends_on:
      - redis
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: shalonapp_flower
    ports:
      - "5555:5555"
      - "6379:6379"
    command: /start-flower