version: "3"

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: shalonapp_django
    container_name: django
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - "3306"
    command: python manage.py runserver 0.0.0.0:8000
