# Generated by Django 4.0 on 2022-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clients_age_alter_clients_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='second_phone',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
