# Generated by Django 4.0 on 2022-08-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clients_second_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='second_phone',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
