# Generated by Django 4.0 on 2022-08-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_options_receipt_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
