# Generated by Django 4.0 on 2022-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
