# Generated by Django 4.0 on 2022-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='number',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
