# Generated by Django 4.0 on 2022-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_alter_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
    ]
