# Generated by Django 4.0 on 2022-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_agenda_id_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='location_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
