# Generated by Django 4.0 on 2022-08-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agenda_id',
            field=models.IntegerField(null=True),
        ),
    ]
