# Generated by Django 4.0 on 2022-08-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.IntegerField(null=True),
        ),
    ]
