# Generated by Django 4.0 on 2022-08-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_payment_agenda_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='employee_name',
            new_name='employee_code_name',
        ),
    ]
