# Generated by Django 4.0 on 2022-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment_transactions',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='payment_transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='payment_transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='amount',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='installments',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
