# Generated by Django 4.0 on 2022-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_payment_transactions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_transactions',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment_transactions',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
