# Generated by Django 4.0 on 2022-08-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_rename_payment_transactions_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='location_id',
            new_name='agenda_location_id',
        ),
    ]
