# Generated by Django 4.0 on 2022-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_rename_location_id_payment_agenda_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='errores',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
    ]
