# Generated by Django 4.0 on 2022-10-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_rename_number_transaction_ticker_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='facturable_electronica',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='change_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto cambio'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee_code_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto empleado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='monto pagado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
    ]
