# Generated by Django 4.0 on 2022-09-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='updated at')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_a', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_b', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_c', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.URLField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='principal', editable=False, max_length=100, unique=True)),
                ('agenda_pro_token', models.CharField(max_length=200)),
                ('siigo_username', models.CharField(max_length=100)),
                ('siigo_access_key', models.CharField(max_length=200)),
                ('siigo_access_token', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
