# Generated by Django 4.0 on 2022-09-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agenda_pro_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='siigo_host',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
