# Generated by Django 4.0 on 2022-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='agenda_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
