# Generated by Django 4.0 on 2022-08-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_agenda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='agenda_id',
        ),
    ]
