# Generated by Django 4.0 on 2022-08-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_clients_agenda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='agenda_id',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
    ]
