# Generated by Django 4.0 on 2022-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clients_agenda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='record_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
