# Generated by Django 4.0 on 2022-08-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clients_age_alter_clients_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_day',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_month',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='record_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
