# Generated by Django 4.0 on 2022-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_clients_options_clients_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='second_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
