# Generated by Django 4.0 on 2022-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_clients_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='clients',
            name='siigo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='dia_nacimiento'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='mes_nacimiento'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ano_nacimiento'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='distrito'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='tipo_docto'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='identification_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='documento'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='record_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='numero_registro'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='second_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telefono_dos'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
    ]
