# Generated by Django 4.0 on 2022-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_clients_options_clients_siigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='consumidor_final',
            field=models.BooleanField(default=False),
        ),
    ]
