# Generated by Django 4.0 on 2022-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_discount_alter_booking_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mock_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='updated at')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('provider', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
