# Generated by Django 4.0 on 2022-08-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_mock_bookings_mockbooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='receipt_id',
        ),
        migrations.RemoveField(
            model_name='mockbooking',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='agenda_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mockbooking',
            name='agenda_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
