# Generated by Django 4.0 on 2022-08-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_agenda_id'),
        ('bookings', '0006_remove_booking_receipt_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockBooking',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='agenda_id',
            new_name='agenda_receipt_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='Receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_session',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
