# Generated by Django 4.0 on 2022-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_end_alter_booking_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='agenda_receipt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
