# Generated by Django 4.0 on 2022-10-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_payment_facturable_electronica_alter_payment_amount_and_more'),
        ('receipts', '0010_alter_receipt_created_at_alter_receipt_updated_at'),
        ('bookings', '0009_alter_booking_agenda_receipt_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='Payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='pago'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt', verbose_name='recibo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agenda_receipt_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='agenda'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_session',
            field=models.BooleanField(blank=True, null=True, verbose_name='es session'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_session_booked',
            field=models.BooleanField(blank=True, null=True, verbose_name='es sesion reservada'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider_lock',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='servicio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='web_origin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='web'),
        ),
    ]
