# Generated by Django 4.0 on 2022-11-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0010_alter_receipt_created_at_alter_receipt_updated_at'),
        ('payments', '0023_payment_comprobante_siigo'),
        ('bookings', '0010_alter_booking_options_alter_booking_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='precio')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='descuento')),
                ('service', models.CharField(blank=True, max_length=200, null=True, verbose_name='servicio')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='proveedor')),
                ('Payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='pago')),
                ('Receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt', verbose_name='recibo')),
            ],
            options={
                'verbose_name': 'reserva_simulada',
                'verbose_name_plural': 'reservas_simuladas',
            },
        ),
    ]
