# Generated by Django 4.0 on 2022-11-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_mockbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockBooking',
        ),
    ]
