# Generated by Django 4.0 on 2022-10-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha cuando fue creado el registro.', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='fecha cuando fue actualizado el registro.', null=True, verbose_name='updated at'),
        ),
    ]
