# Generated by Django 4.0 on 2022-08-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_bookings_end_alter_bookings_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_origin', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_lock', models.CharField(blank=True, max_length=200, null=True)),
                ('is_session_booked', models.BooleanField(blank=True, null=True)),
                ('notes', models.CharField(help_text='Bienvenido(a) a Shalon Lash Brow , Por favor llegar 5 min antes.', max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('service', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('receipt_id', models.IntegerField(null=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
